version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${USER_ID}:8765"  # Dynamically bind user ID as the external port
    environment:
      - USER_ID=${USER_ID}  # Pass user ID as an environment variable
      - PORT=${USER_ID}  # Set the port dynamically
    volumes:
      - ./cert:/app/cert
      - ./frontend:/app/frontend
      - ./src:/app/src
