version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${USER_ID}:8765"  # Dynamically map port using the USER_ID environment variable
    volumes:
      - ./cert:/app/cert
      - ./frontend:/app/frontend
      - ./src:/app/src
      # Mount /var/log only if it exists (for Linux users)
      - /var/log:/host_logs:ro
    pid: "host"
    privileged: true  # Run in privileged mode
    environment:
      - ENVIRONMENT=production
      - USER_ID=${USER_ID}  # Pass the Linux user ID dynamically to the container
