services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
    volumes:
      - ./cert:/app/cert
      - ./frontend:/app/frontend
      - ./src:/app/src
      - /var/log:/host_logs:ro
    pid: "host"
    privileged: true 
    environment:
      - ENVIRONMENT=production
