version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
    volumes:
      - ./cert:/app/cert
      - ./frontend:/app/frontend
      - ./src:/app/src
      # Mount /var/log only if it exists (for Linux users)
      - /var/log:/host_logs:ro
    environment:
      - ENVIRONMENT=development
